name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    uses: hasundue/actions/.github/workflows/test-deno.yml@main
    secrets: inherit

  integration:
    name: Integration
    uses: hasundue/actions/.github/workflows/integration-deno.yml@main
    secrets: inherit
