name: Release

on:
  push:
    branches:
      - main
    paths:
      - '**/deno.json'
  workflow_dispatch:

run-name: >-
  ${{ github.event_name == 'workflow_dispatch'
  && 'manual release'
  || github.event.head_commit.message }}

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore: release')"

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Setup actions/cache for Deno
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno
          key: ubuntu-latest-deno-${{ hashFiles('./deno.lock') }}
          restore-keys: ubuntu-latest-deno

      - name: Setup actions/cache for Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ./core/deno_lockfile/target
          key: ubuntu-latest-cargo-${{ hashFiles('./**/Cargo.lock') }}
          restore-keys: ubuntu-latest-cargo

      - name: Build core/deno_lockfile
        run: |
          cd core/deno_lockfile
          deno task build

      - name: Publish packages to JSR
        run: npx jsr publish
