name: Update

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

run-name: >-
  ${{ github.event_name == 'workflow_dispatch'
  && 'manual update'
  || 'scheduled update' }}

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hasundue/molt-action@v1
        with:
          token: ${{ secrets.PAT_UPDATE }}
